### ISSUE TITLE
[bug] stuck "loading"

### ISSUE THREAD

**Issue by fischerando** [jalehman/port#153] opened 2021-12-06 14:06 UTC
**Bug Description**
When I hit the "Launch" button, Port shows me its nice loading animation (black screen, white circle with white thing spinning) and then never changes from that state. The URL is file:///C:/Users/redacted/AppData/Local/port/app-1.6.0/resources/app/.webpack/renderer/main_window/index.html#/pier/shipname/launch

**To Reproduce**
1. Use Port happily for months. It's killer!
2. Click on "Launch"
3. Wait X hours
4. Still loading

**Expected Behavior**
My ship launches and I get to start using it

**Environment:**
 - OS: Windows
 - Version: 11
 - Port Version: 1.6.0

**Additional context**
Can't click on the little debugging bug from this window, sorry.

**Comment by arthyn** [comment] 2021-12-06 15:48
I think this is a duplicate of #152. I'll check it out, thanks!

**Comment by PR0M3TH3AN** [comment] 2021-12-08 02:23
I am also having this exact issue. Is it safe to "launch" this Pier the old fashioned way again? Have been waiting for hours. Still loading. I have a lot of groups on this Pier and will be very discouraged if lost. Using Windows 10 btw

**Comment by arthyn** [comment] 2021-12-23 06:49
Should be fixed in latest update

**Closed as completed by arthyn** 2021-12-23 06:49 UTC
Labels: bug
